###
# File: openlb.yaml
# Author: Ming Cheng<mingcheng@outlook.com>
#
# Created Date: Sunday, July 24th 2022, 8:51:52 pm
# Last Modified: Monday, August 8th 2022, 12:17:05 pm
#
# http://www.opensource.org/licenses/MIT
###

# ref: https://openelb.io/docs/getting-started/configuration/configure-ip-address-pools-using-eip/

apiVersion: network.kubesphere.io/v1alpha2
kind: Eip
metadata:
  name: eip-pool
  annotations:
    eip.openelb.kubesphere.io/is-default-eip: "true"
spec:
  address: 172.16.0.90-172.16.0.99
  protocol: layer2
  disable: false
  interface: eth0
