###
# File: server.yaml
# Author: Ming Cheng<mingcheng@outlook.com>
#
# Created Date: Wednesday, August 3rd 2022, 3:15:47 pm
# Last Modified: Tuesday, August 9th 2022, 1:34:40 am
#
# http://www.opensource.org/licenses/MIT
###

apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    lb.kubesphere.io/v1alpha1: openelb
    protocol.openelb.kubesphere.io/v1alpha1: layer2
    eip.openelb.kubesphere.io/v1alpha2: eip-pool
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.99
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx
