apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dnsutils
  labels:
    tier: management
    app: dnsutils
spec:
  selector:
    matchLabels:
      name: dnsutils
  template:
    metadata:
      labels:
        name: dnsutils
    spec:
      containers:
        - image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
          name: dnsutils
          command: ["sh", "-c", "nslookup kubernetes.default && sleep 3600"]
