###
# File: kubeadm-init1.24.yaml
# Author: Ming Cheng<mingcheng@outlook.com>
#
# Created Date: Tuesday, August 2nd 2022, 4:26:56 pm
# Last Modified: Monday, August 8th 2022, 12:30:31 am
#
# http://www.opensource.org/licenses/MIT
###

apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.0.200
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  imagePullPolicy: Always
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
controlPlaneEndpoint: 192.168.0.200:6443
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
kubernetesVersion: stable
networking:
  podSubnet: "10.244.0.0/24"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
maxPods: 1024
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
ipvs:
  strictARP: true
