###
# File: kubeadm-init.yaml
# Author: Ming Cheng<mingcheng@outlook.com>
#
# Created Date: Tuesday, August 2nd 2022, 4:33:13 pm
# Last Modified: Tuesday, August 2nd 2022, 10:01:49 pm
#
# http://www.opensource.org/licenses/MIT
###

apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 10.0.10.205
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  timeoutForControlPlane: 4m0s
  certSANs:
    - 10.0.10.205
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
kubernetesVersion: stable
#kubernetesVersion: latest
networking:
  podSubnet: 10.95.0.0/16
  # serviceSubnet: 10.96.0.0/16
  # dnsDomain: cluster.local
controlPlaneEndpoint: 10.0.10.205
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
# kubelet specific options here
maxPods: 256
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
# kube-proxy specific options here
mode: "ipvs"
ipvs:
  strictARP: true
