apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
  # annotations:
  #   lb.kubesphere.io/v1alpha1: openelb
  #   protocol.openelb.kubesphere.io/v1alpha1: layer2
  #   eip.openelb.kubesphere.io/v1alpha2: eip-pool
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.210
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  externalTrafficPolicy: Cluster
  selector:
    app: helloworld
