apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
        # this toleration is to have the daemonset runnable on master nodes
        # remove it if your masters can't run pods
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  # annotations:
  #   lb.kubesphere.io/v1alpha1: openelb
  #   protocol.openelb.kubesphere.io/v1alpha1: layer2
  #   eip.openelb.kubesphere.io/v1alpha2: eip-pool
spec:
  # type: ClusterIP
  # loadBalancerIP: 192.168.0.210
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx
