###
# File: address-pools.yaml
# Author: Ming Cheng<mingcheng@outlook.com>
#
# Created Date: Tuesday, July 5th 2022, 2:18:22 pm
# Last Modified: Tuesday, July 5th 2022, 2:21:02 pm
#
# http://www.opensource.org/licenses/MIT
###


apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.0.10.100-10.0.10.109
